"""Webchat channel — first-party, no external dependencies.

Tenant resolution: integrations row (provider="webchat", kind="channel")
whose config.public_key matches the widget key.
Customer identity: visitor session key generated by the widget.
"""

from __future__ import annotations

import uuid

from app.modules.conversations.gateway.base import (
    ChannelAdapter,
    InboundMessage,
    OutboundMessage,
    ProviderCredentials,
)


class WebchatAdapter(ChannelAdapter):
    name = "webchat"

    def verify_request(self, query_params: dict[str, str]) -> str | None:
        return None  # no handshake needed

    def check_signature(self, headers: dict[str, str], raw_body: bytes) -> bool:
        return True  # first-party widget; auth is the public key + rate limits

    def parse_inbound(self, payload: dict) -> list[InboundMessage]:
        session_key = str(payload.get("session_key", "")).strip()
        body = str(payload.get("body", "")).strip()
        if not session_key or not body:
            return []
        return [
            InboundMessage(
                channel=self.name,
                channel_message_id=payload.get("client_message_id"),
                customer_ref=session_key,
                customer_name=payload.get("visitor_name"),
                body=body,
                raw=payload,
            )
        ]

    def resolve_tenant_key(self, payload: dict) -> str | None:
        return payload.get("public_key")

    async def send(self, credentials: ProviderCredentials, message: OutboundMessage) -> str:
        # Delivery for webchat is pull-based (the widget polls / fetches via SSE),
        # so "sending" just means persisting — the message row is the transport.
        return f"webchat-{uuid.uuid4()}"


webchat_adapter = WebchatAdapter()
