"""segments table

Revision ID: 24037e2ebc05
Revises: 48528b41d6db
Create Date: 2026-09-18 22:16:48.883442

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "24037e2ebc05"
down_revision: str | None = "48528b41d6db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
