"""w2 identity merge templates attachments privacy

Revision ID: 49303e2e2dd0
Revises: d0d649ee05cb
Create Date: 2026-09-18 21:11:35.204042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49303e2e2dd0'
down_revision: Union[str, None] = 'd0d649ee05cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='draft', nullable=False),
    sa.Column('language', sa.String(length=15), server_default='ar', nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('provider', sa.String(length=31), server_default='whatsapp', nullable=False),
    sa.Column('provider_template_id', sa.String(length=127), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'language', name='uq_templates_tenant_name_lang')
    )
    op.create_index(op.f('ix_message_templates_tenant_id'), 'message_templates', ['tenant_id'], unique=False)
    op.create_index('ix_templates_tenant_status', 'message_templates', ['tenant_id', 'status'], unique=False)
    op.create_table('retention_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_class', sa.String(length=63), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='active', nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retention_policies_tenant_class', 'retention_policies', ['tenant_id', 'data_class'], unique=False)
    op.create_index(op.f('ix_retention_policies_tenant_id'), 'retention_policies', ['tenant_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=31), nullable=False),
    sa.Column('purpose', sa.String(length=63), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='granted', nullable=False),
    sa.Column('source', sa.String(length=63), nullable=True),
    sa.Column('proof', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consents_tenant_customer_purpose', 'consents', ['tenant_id', 'customer_id', 'purpose'], unique=False)
    op.create_index(op.f('ix_consents_tenant_id'), 'consents', ['tenant_id'], unique=False)
    op.create_table('data_subject_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='pending', nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('payload_scope', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result_ref', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_subject_requests_tenant_id'), 'data_subject_requests', ['tenant_id'], unique=False)
    op.create_index('ix_dsr_tenant_status', 'data_subject_requests', ['tenant_id', 'status'], unique=False)
    op.create_table('identity_merge_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_a_id', sa.UUID(), nullable=False),
    sa.Column('customer_b_id', sa.UUID(), nullable=False),
    sa.Column('match_type', sa.String(length=31), server_default='ai_suggested', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=15), server_default='pending', nullable=False),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_a_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_b_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'customer_a_id', 'customer_b_id', name='uq_merge_candidates_pair')
    )
    op.create_index(op.f('ix_identity_merge_candidates_tenant_id'), 'identity_merge_candidates', ['tenant_id'], unique=False)
    op.create_index('ix_merge_candidates_tenant_status', 'identity_merge_candidates', ['tenant_id', 'status'], unique=False)
    op.create_table('identity_merge_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_customer_id', sa.UUID(), nullable=False),
    sa.Column('merged_away_customer_id', sa.UUID(), nullable=False),
    sa.Column('performed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=31), server_default='human', nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merged_away_customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_merge_events_tenant_id'), 'identity_merge_events', ['tenant_id'], unique=False)
    op.create_index('ix_merge_events_tenant_canonical', 'identity_merge_events', ['tenant_id', 'canonical_customer_id'], unique=False)
    op.create_table('template_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='submitted', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=63), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_approvals_tenant_id'), 'template_approvals', ['tenant_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('provider_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=127), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('scan_status', sa.String(length=15), server_default='pending', nullable=False),
    sa.Column('processing_status', sa.String(length=15), server_default='pending', nullable=False),
    sa.Column('transcription_status', sa.String(length=15), nullable=True),
    sa.Column('transcript_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(length=15), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_tenant_conversation', 'attachments', ['tenant_id', 'conversation_id'], unique=False)
    op.create_index(op.f('ix_attachments_tenant_id'), 'attachments', ['tenant_id'], unique=False)
    op.create_index('ix_attachments_tenant_message', 'attachments', ['tenant_id', 'message_id'], unique=False)
    op.add_column('customers', sa.Column('merged_into_customer_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('deletion_reason', sa.String(length=255), nullable=True))
    op.create_index('ix_customers_tenant_merged_into', 'customers', ['tenant_id', 'merged_into_customer_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'customers', ['merged_into_customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index('ix_customers_tenant_merged_into', table_name='customers')
    op.drop_column('customers', 'deletion_reason')
    op.drop_column('customers', 'deleted_by')
    op.drop_column('customers', 'deleted_at')
    op.drop_column('customers', 'merged_at')
    op.drop_column('customers', 'merged_into_customer_id')
    op.drop_index('ix_attachments_tenant_message', table_name='attachments')
    op.drop_index(op.f('ix_attachments_tenant_id'), table_name='attachments')
    op.drop_index('ix_attachments_tenant_conversation', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_template_approvals_tenant_id'), table_name='template_approvals')
    op.drop_table('template_approvals')
    op.drop_index('ix_merge_events_tenant_canonical', table_name='identity_merge_events')
    op.drop_index(op.f('ix_identity_merge_events_tenant_id'), table_name='identity_merge_events')
    op.drop_table('identity_merge_events')
    op.drop_index('ix_merge_candidates_tenant_status', table_name='identity_merge_candidates')
    op.drop_index(op.f('ix_identity_merge_candidates_tenant_id'), table_name='identity_merge_candidates')
    op.drop_table('identity_merge_candidates')
    op.drop_index('ix_dsr_tenant_status', table_name='data_subject_requests')
    op.drop_index(op.f('ix_data_subject_requests_tenant_id'), table_name='data_subject_requests')
    op.drop_table('data_subject_requests')
    op.drop_index(op.f('ix_consents_tenant_id'), table_name='consents')
    op.drop_index('ix_consents_tenant_customer_purpose', table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_retention_policies_tenant_id'), table_name='retention_policies')
    op.drop_index('ix_retention_policies_tenant_class', table_name='retention_policies')
    op.drop_table('retention_policies')
    op.drop_index('ix_templates_tenant_status', table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_tenant_id'), table_name='message_templates')
    op.drop_table('message_templates')
    # ### end Alembic commands ###
