"""w3 ai governance approvals budgets policies handovers evaluations

Revision ID: 6c21c03cfd6a
Revises: 49303e2e2dd0
Create Date: 2026-09-18 21:13:50.844195

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c21c03cfd6a"
down_revision: str | None = "49303e2e2dd0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_provider_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=31), nullable=False),
        sa.Column("status", sa.String(length=15), server_default="allowed", nullable=False),
        sa.Column(
            "allowed_models",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("pii_redaction_required", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "data_classification", sa.String(length=31), server_default="internal", nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "provider", name="uq_ai_provider_policy"),
    )
    op.create_index(
        op.f("ix_ai_provider_policies_tenant_id"),
        "ai_provider_policies",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "ai_budget_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(length=15), server_default="tenant", nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("period", sa.String(length=15), server_default="monthly", nullable=False),
        sa.Column(
            "hard_cap", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("warning_threshold", sa.Integer(), nullable=False),
        sa.Column("on_exceed", sa.String(length=15), server_default="block", nullable=False),
        sa.Column("fallback_alias", sa.String(length=31), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "scope", "period", "agent_id", name="uq_budget_scope"),
    )
    op.create_index(
        op.f("ix_ai_budget_policies_tenant_id"), "ai_budget_policies", ["tenant_id"], unique=False
    )
    op.create_table(
        "ai_evaluations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("prompt_version", sa.Integer(), nullable=False),
        sa.Column("dataset_ref", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=15), server_default="pending", nullable=False),
        sa.Column(
            "quality_metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("rollout_status", sa.String(length=15), server_default="none", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_evaluations_tenant_id"), "ai_evaluations", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_evaluations_tenant_agent",
        "ai_evaluations",
        ["tenant_id", "agent_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "ai_handovers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.String(length=31), nullable=False),
        sa.Column("status", sa.String(length=15), server_default="pending", nullable=False),
        sa.Column("claimed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["claimed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_handovers_tenant_id"), "ai_handovers", ["tenant_id"], unique=False)
    op.create_index(
        "ix_handovers_tenant_status",
        "ai_handovers",
        ["tenant_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "approval_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("requested_by", sa.String(length=31), server_default="ai", nullable=False),
        sa.Column("entity_type", sa.String(length=63), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=127), nullable=False),
        sa.Column("risk_level", sa.String(length=15), server_default="HIGH", nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("status", sa.String(length=15), server_default="PENDING", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["approved_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_requests_tenant_id"), "approval_requests", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_approvals_tenant_status",
        "approval_requests",
        ["tenant_id", "status", "expires_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_approvals_tenant_status", table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_tenant_id"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index("ix_handovers_tenant_status", table_name="ai_handovers")
    op.drop_index(op.f("ix_ai_handovers_tenant_id"), table_name="ai_handovers")
    op.drop_table("ai_handovers")
    op.drop_index("ix_evaluations_tenant_agent", table_name="ai_evaluations")
    op.drop_index(op.f("ix_ai_evaluations_tenant_id"), table_name="ai_evaluations")
    op.drop_table("ai_evaluations")
    op.drop_index(op.f("ix_ai_budget_policies_tenant_id"), table_name="ai_budget_policies")
    op.drop_table("ai_budget_policies")
    op.drop_index(op.f("ix_ai_provider_policies_tenant_id"), table_name="ai_provider_policies")
    op.drop_table("ai_provider_policies")
    # ### end Alembic commands ###
