"""automation workflows domain

Revision ID: 6cd2037d7891
Revises: 24037e2ebc05
Create Date: 2026-09-19 00:09:30.457267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cd2037d7891'
down_revision: Union[str, None] = '24037e2ebc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_event', sa.String(length=127), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='draft', nullable=False),
    sa.Column('execution_backend', sa.String(length=15), server_default='internal', nullable=False),
    sa.Column('n8n_workflow_ref', sa.String(length=255), nullable=True),
    sa.Column('current_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_tenant_id'), 'workflows', ['tenant_id'], unique=False)
    op.create_index('ix_workflows_tenant_trigger', 'workflows', ['tenant_id', 'trigger_event', 'status'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('workflow_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='running', nullable=False),
    sa.Column('trigger_event_type', sa.String(length=127), nullable=True),
    sa.Column('trigger_event_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wf_exec_tenant_workflow_started', 'workflow_executions', ['tenant_id', 'workflow_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_workflow_executions_tenant_id'), 'workflow_executions', ['tenant_id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_workflow_versions_workflow_version', 'workflow_versions', ['workflow_id', 'version'], unique=True)
    op.create_table('workflow_failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.String(length=127), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('resolution', sa.String(length=31), server_default='dead', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wf_failures_execution', 'workflow_failures', ['execution_id'], unique=False)
    op.create_index(op.f('ix_workflow_failures_tenant_id'), 'workflow_failures', ['tenant_id'], unique=False)
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=31),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.add_column('integrations', sa.Column('webhook_health', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('messages', sa.Column('content_type', sa.String(length=31), server_default='text', nullable=False))
    op.add_column('messages', sa.Column('reply_to_message_id', sa.UUID(), nullable=True))
    op.add_column('messages', sa.Column('edited', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('messages', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('messages', sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False))
    op.create_index('ix_messages_tenant_reply_to', 'messages', ['tenant_id', 'reply_to_message_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index('ix_messages_tenant_reply_to', table_name='messages')
    op.drop_column('messages', 'provider_metadata')
    op.drop_column('messages', 'deleted')
    op.drop_column('messages', 'edited')
    op.drop_column('messages', 'reply_to_message_id')
    op.drop_column('messages', 'content_type')
    op.drop_column('integrations', 'webhook_health')
    op.alter_column('conversations', 'status',
               existing_type=sa.String(length=31),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.drop_index(op.f('ix_workflow_failures_tenant_id'), table_name='workflow_failures')
    op.drop_index('ix_wf_failures_execution', table_name='workflow_failures')
    op.drop_table('workflow_failures')
    op.drop_index('uq_workflow_versions_workflow_version', table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index(op.f('ix_workflow_executions_tenant_id'), table_name='workflow_executions')
    op.drop_index('ix_wf_exec_tenant_workflow_started', table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index('ix_workflows_tenant_trigger', table_name='workflows')
    op.drop_index(op.f('ix_workflows_tenant_id'), table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
