"""operations tasks sla calendars

Revision ID: 7f83fc4604fa
Revises: c5c6fc1ae836
Create Date: 2026-09-19 03:04:03.161179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f83fc4604fa'
down_revision: Union[str, None] = 'c5c6fc1ae836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=63), server_default='Africa/Cairo', nullable=False),
    sa.Column('hours', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('holidays', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_calendars_tenant_id'), 'business_calendars', ['tenant_id'], unique=False)
    op.create_index('ix_calendars_tenant', 'business_calendars', ['tenant_id', 'is_default'], unique=False)
    op.create_table('sla_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('first_response_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), server_default='1440', nullable=False),
    sa.Column('applies_to_channel', sa.String(length=31), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=15), server_default='active', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sla_policies_tenant', 'sla_policies', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_sla_policies_tenant_id'), 'sla_policies', ['tenant_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='2', nullable=False),
    sa.Column('status', sa.String(length=15), server_default='todo', nullable=False),
    sa.Column('related_entity_type', sa.String(length=63), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=15), server_default='human', nullable=False),
    sa.Column('created_by', sa.String(length=63), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_tenant_due', 'tasks', ['tenant_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_index('ix_tasks_tenant_status_assignee', 'tasks', ['tenant_id', 'status', 'assignee_user_id'], unique=False)
    op.create_table('sla_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=31), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='running', nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('met_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['sla_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_events_tenant_id'), 'sla_events', ['tenant_id'], unique=False)
    op.create_index('ix_sla_events_tenant_status_deadline', 'sla_events', ['tenant_id', 'status', 'deadline_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sla_events_tenant_status_deadline', table_name='sla_events')
    op.drop_index(op.f('ix_sla_events_tenant_id'), table_name='sla_events')
    op.drop_table('sla_events')
    op.drop_index('ix_tasks_tenant_status_assignee', table_name='tasks')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index('ix_tasks_tenant_due', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_sla_policies_tenant_id'), table_name='sla_policies')
    op.drop_index('ix_sla_policies_tenant', table_name='sla_policies')
    op.drop_table('sla_policies')
    op.drop_index('ix_calendars_tenant', table_name='business_calendars')
    op.drop_index(op.f('ix_business_calendars_tenant_id'), table_name='business_calendars')
    op.drop_table('business_calendars')
    # ### end Alembic commands ###
