"""w4w6 platform infra eventlog processed scheduled delivery dedupe security secrets flags metrics

Revision ID: 8a1f6fb95fc6
Revises: 6c21c03cfd6a
Create Date: 2026-09-18 21:16:47.510022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a1f6fb95fc6'
down_revision: Union[str, None] = '6c21c03cfd6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_message_dedupe',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('channel_account_id', sa.String(length=127), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel_account_id', 'external_message_id', name='uq_inbound_dedupe')
    )
    op.create_table('processed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consumer_name', sa.String(length=63), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='done', nullable=False),
    sa.Column('result_reference', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consumer_name', 'event_id', name='uq_processed_consumer_event')
    )
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=63), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_events_type_created', 'security_events', ['event_type', 'created_at'], unique=False)
    op.create_table('event_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=127), nullable=False),
    sa.Column('aggregate_type', sa.String(length=63), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=True),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('producer', sa.String(length=63), server_default='core', nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('causation_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_event_log_event_id')
    )
    op.create_index('ix_event_log_aggregate', 'event_log', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index(op.f('ix_event_log_tenant_id'), 'event_log', ['tenant_id'], unique=False)
    op.create_index('ix_event_log_tenant_type_created', 'event_log', ['tenant_id', 'event_type', 'created_at'], unique=False)
    op.create_table('feature_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature', sa.String(length=127), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('role_code', sa.String(length=63), nullable=True),
    sa.Column('rollout_percent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'feature', name='uq_feature_flags_tenant_feature')
    )
    op.create_index(op.f('ix_feature_flags_tenant_id'), 'feature_flags', ['tenant_id'], unique=False)
    op.create_table('metric_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=63), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('timezone_rule', sa.String(length=63), nullable=True),
    sa.Column('currency_rule', sa.String(length=15), nullable=True),
    sa.Column('refund_treatment', sa.String(length=31), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name='uq_metric_defs')
    )
    op.create_index(op.f('ix_metric_definitions_tenant_id'), 'metric_definitions', ['tenant_id'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=63), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='queued', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_scheduled_jobs_idem')
    )
    op.create_index('ix_scheduled_jobs_due', 'scheduled_jobs', ['status', 'run_at'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_tenant_id'), 'scheduled_jobs', ['tenant_id'], unique=False)
    op.create_table('secret_references',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=63), nullable=False),
    sa.Column('provider', sa.String(length=31), nullable=False),
    sa.Column('vault_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=15), server_default='active', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'scope', name='uq_secret_ref')
    )
    op.create_index(op.f('ix_secret_references_tenant_id'), 'secret_references', ['tenant_id'], unique=False)
    op.create_table('delivery_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('webhook_delivery_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=31), nullable=False),
    sa.Column('outcome', sa.String(length=15), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_delivery_id'], ['webhook_deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delivery_attempts_message', 'delivery_attempts', ['tenant_id', 'message_id'], unique=False)
    op.create_index(op.f('ix_delivery_attempts_tenant_id'), 'delivery_attempts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_attempts_tenant_id'), table_name='delivery_attempts')
    op.drop_index('ix_delivery_attempts_message', table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    op.drop_index(op.f('ix_secret_references_tenant_id'), table_name='secret_references')
    op.drop_table('secret_references')
    op.drop_index(op.f('ix_scheduled_jobs_tenant_id'), table_name='scheduled_jobs')
    op.drop_index('ix_scheduled_jobs_due', table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_metric_definitions_tenant_id'), table_name='metric_definitions')
    op.drop_table('metric_definitions')
    op.drop_index(op.f('ix_feature_flags_tenant_id'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index('ix_event_log_tenant_type_created', table_name='event_log')
    op.drop_index(op.f('ix_event_log_tenant_id'), table_name='event_log')
    op.drop_index('ix_event_log_aggregate', table_name='event_log')
    op.drop_table('event_log')
    op.drop_index('ix_security_events_type_created', table_name='security_events')
    op.drop_table('security_events')
    op.drop_table('processed_events')
    op.drop_table('inbound_message_dedupe')
    # ### end Alembic commands ###
