"""w1 webhook_events reservations version columns

Revision ID: b8befbde56e7
Revises: 6347b9fd0e07
Create Date: 2026-09-18 20:42:46.792813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8befbde56e7'
down_revision: Union[str, None] = '6347b9fd0e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=31), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_status', sa.String(length=15), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_events_provider_ext', 'webhook_events', ['provider', 'external_event_id'], unique=False)
    op.create_index('ix_webhook_events_status_created', 'webhook_events', ['processing_status', 'received_at'], unique=False)
    op.add_column('agents', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('campaigns', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('customers', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('order_payments', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('orders', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('refunds', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refunds', 'version')
    op.drop_column('orders', 'version')
    op.drop_column('order_payments', 'version')
    op.drop_column('customers', 'version')
    op.drop_column('campaigns', 'version')
    op.drop_column('agents', 'version')
    op.drop_index('ix_webhook_events_status_created', table_name='webhook_events')
    op.drop_index('ix_webhook_events_provider_ext', table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
