"""ANN indexes for the pgvector embedding columns (§39)

Revision ID: b8c9d0e1f2a3
Revises: a7b8c9d0e1f2
Create Date: 2026-09-20

``knowledge_items.embedding`` and ``memories.embedding`` are ``Vector(1536)``
and BOTH are queried by cosine distance (``<=>``): see
``app/modules/ai/knowledge.py`` — ``KnowledgeItem.embedding.cosine_distance(...)``
and ``Memory.embedding.cosine_distance(...)``. With no index, every similarity
search is an EXACT scan: Postgres reads and compares all 1536 floats of every
row for the tenant before it can order by distance. That is acceptable for a
few hundred rows and untenable at scale — the scan is linear in row count and
the vectors are large, so latency and I/O grow without bound as tenants ingest.

An HNSW index turns that into an approximate nearest-neighbour lookup whose cost
is roughly logarithmic in row count, with the recall/speed tradeoff set by
``hnsw.ef_search`` at query time. ``vector_cosine_ops`` is required because the
queries order by cosine distance; an L2 (``vector_l2_ops``) index would simply
not be used by those queries.

Cost, stated plainly:
- Building the index is expensive in TIME and MEMORY (HNSW is built in memory);
  on a large table this is a long, memory-hungry operation, which is why it is
  an explicit, reviewable migration rather than something autogenerated.
- The index adds write amplification: every INSERT/UPDATE that writes an
  embedding also updates the graph.

``IF NOT EXISTS`` keeps the migration idempotent on databases where the index
was already created out-of-band. Indexes are named so they can be dropped
unambiguously in ``downgrade()``.

One statement per ``op.execute()`` — asyncpg's extended-query protocol rejects
multiple commands in a single call, so each CREATE/DROP is its own execute.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "b8c9d0e1f2a3"
down_revision: str | None = "a7b8c9d0e1f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # knowledge_items — cosine ANN index (queries use cosine_distance / <=>).
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_knowledge_items_embedding_hnsw "
        "ON knowledge_items USING hnsw (embedding vector_cosine_ops)"
    )
    # memories — same distance operator, same index family.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_memories_embedding_hnsw "
        "ON memories USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_memories_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_knowledge_items_embedding_hnsw")
