"""w7b knowledge visibility memory governance

Revision ID: c5c6fc1ae836
Revises: f8a1c2d3e4b5
Create Date: 2026-09-19 00:50:25.425093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c6fc1ae836'
down_revision: Union[str, None] = 'f8a1c2d3e4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_items', sa.Column('visibility', sa.String(length=15), server_default='customer_facing', nullable=False))
    op.add_column('memories', sa.Column('source', sa.String(length=31), server_default='customer_stated', nullable=False))
    op.add_column('memories', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('memories', sa.Column('confidence', sa.Numeric(precision=5, scale=4), server_default='0.5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'confidence')
    op.drop_column('memories', 'verified_at')
    op.drop_column('memories', 'source')
    op.drop_column('knowledge_items', 'visibility')
    # ### end Alembic commands ###
