"""inventory_reservations table

Revision ID: d0d649ee05cb
Revises: b8befbde56e7
Create Date: 2026-09-18 20:46:30.725326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d649ee05cb'
down_revision: Union[str, None] = 'b8befbde56e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_reservations',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=15), server_default='ACTIVE', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inv_res_status_expires', 'inventory_reservations', ['status', 'expires_at'], unique=False)
    op.create_index('ix_inv_res_tenant_variant_status', 'inventory_reservations', ['tenant_id', 'variant_id', 'status'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_tenant_id'), 'inventory_reservations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_reservations_tenant_id'), table_name='inventory_reservations')
    op.drop_index('ix_inv_res_tenant_variant_status', table_name='inventory_reservations')
    op.drop_index('ix_inv_res_status_expires', table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    # ### end Alembic commands ###
