// Static channel presentation metadata only. Connection status and all
// conversations/messages are loaded from the authenticated backend API.

export const CHANNELS = [
  {
    id: "whatsapp",
    name: "WhatsApp",
    icon: "MessageCircle",
    accent: "#25D366",
    theme: {
      headerBg: "#075E54",
      headerText: "#ffffff",
      chatBg: "#E5DDD5",
      out: "#DCF8C6",
      outText: "#111111",
      in: "#ffffff",
      inText: "#111111",
      inputBg: "#f0f2f5",
      inputBorder: "#e9edef",
      checkmarks: true,
      tail: true,
    },
  },
  {
    id: "instagram",
    name: "Instagram",
    icon: "Instagram",
    accent: "#E1306C",
    theme: {
      headerBg: "linear-gradient(135deg, #515BD4 0%, #8134AF 30%, #DD2A7B 60%, #F58529 100%)",
      headerText: "#ffffff",
      chatBg: "#ffffff",
      out: "linear-gradient(135deg, #833AB4, #E1306C)",
      outText: "#ffffff",
      in: "#EFEFEF",
      inText: "#111111",
      inputBg: "#ffffff",
      inputBorder: "#dbdbdb",
      checkmarks: false,
      tail: false,
    },
  },
  {
    id: "messenger",
    name: "Messenger",
    icon: "MessagesSquare",
    accent: "#0084FF",
    theme: {
      headerBg: "#0084FF",
      headerText: "#ffffff",
      chatBg: "#ffffff",
      out: "#0084FF",
      outText: "#ffffff",
      in: "#F1F0F0",
      inText: "#111111",
      inputBg: "#f0f2f5",
      inputBorder: "#e9edef",
      checkmarks: true,
      tail: false,
    },
  },
  {
    id: "webchat",
    name: "Web Chat",
    icon: "MessageSquare",
    accent: "hsl(var(--primary))",
    theme: "app",
  },
  {
    id: "telegram",
    name: "Telegram",
    icon: "Send",
    accent: "#2AABEE",
    theme: {
      headerBg: "#527DA3",
      headerText: "#ffffff",
      chatBg: "#E7F3FE",
      out: "#E8F5FC",
      outText: "#111111",
      in: "#ffffff",
      inText: "#111111",
      inputBg: "#ffffff",
      inputBorder: "#e1eaf0",
      checkmarks: true,
      tail: false,
    },
  },
  {
    id: "facebook",
    name: "Facebook",
    icon: "Facebook",
    accent: "#1877F2",
    theme: {
      headerBg: "#1877F2",
      headerText: "#ffffff",
      chatBg: "#ffffff",
      out: "#1877F2",
      outText: "#ffffff",
      in: "#F1F0F0",
      inText: "#111111",
      inputBg: "#f0f2f5",
      inputBorder: "#e9edef",
      checkmarks: true,
      tail: false,
    },
  },
];

export function getChannel(id) {
  return CHANNELS.find((c) => c.id === id) || CHANNELS[0];
}
