/** Shared Arabic vocabulary — reuse exact terms across screens (no half-translated UI). */

export const t = {
  brand: "سيلز أو إس",
  // nav
  dashboard: "الرئيسية",
  inbox: "المحادثات",
  products: "المنتجات",
  inventory: "المخزون",
  orders: "الطلبات",
  customers: "العملاء",
  marketing: "التسويق",
  ai: "الذكاء الاصطناعي",
  settings: "الإعدادات",
  logout: "تسجيل الخروج",
  // auth
  login: "تسجيل الدخول",
  register: "حساب جديد",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  fullName: "الاسم بالكامل",
  storeName: "اسم المتجر",
  // inbox
  conversations: "المحادثات",
  writeReply: "اكتب ردك…",
  send: "إرسال",
  noConversations: "لا توجد محادثات بعد",
  selectConversation: "اختر محادثة لعرضها",
  // products
  addProduct: "إضافة منتج",
  productTitle: "اسم المنتج",
  price: "السعر",
  sku: "رمز SKU",
  status: "الحالة",
  active: "مفعّل",
  draft: "مسودة",
  archived: "مؤرشف",
  // inventory
  onHand: "الكمية المتاحة",
  reserved: "محجوز",
  warehouse: "المخزن",
  quantity: "الكمية",
  recordMovement: "تسجيل حركة",
  in: "إضافة",
  out: "صرف",
  adjust: "تسوية",
  // orders
  createOrder: "إنشاء طلب",
  orderNumber: "رقم الطلب",
  grandTotal: "الإجمالي",
  customer: "العميل",
  pending: "قيد الانتظار",
  confirmed: "مؤكد",
  processing: "قيد التجهيز",
  shipped: "تم الشحن",
  delivered: "تم التسليم",
  completed: "مكتمل",
  cancelled: "ملغي",
  refunded: "مسترد",
  // ai
  knowledge: "قاعدة المعرفة",
  addKnowledge: "إضافة معرفة",
  searchKnowledge: "بحث في المعرفة",
  agents: "الوكلاء",
  usageCost: "الاستهلاك والتكلفة",
  // settings
  team: "الفريق",
  invite: "دعوة عضو",
  role: "الدور",
  owner: "المالك",
  manager: "مدير",
  staff: "موظف",
  integrations: "التكاملات",
  // generic
  save: "حفظ",
  cancel: "إلغاء",
  loading: "جارٍ التحميل…",
  actions: "إجراءات",
  date: "التاريخ",
  total: "الإجمالي",
} as const;
