/** Shared vocabulary — bilingual (ar default / en) via a language-aware
 * proxy. The LAYOUT never flips (direction stays RTL per directive); only
 * strings switch. Screens keep `import { t }` unchanged. */

import { makeT, type Lang } from "@/lib/i18n";
const ar = {
  brand: "FIHRIST",
  // nav groups (§89)
  groupHome: "الرئيسية",
  groupWork: "المحادثات",
  groupBusiness: "الأعمال",
  groupGrowth: "النمو",
  groupAi: "الذكاء الاصطناعي",
  groupAdmin: "الإدارة",
  // nav items
  dashboard: "الرئيسية",
  inbox: "المحادثات",
  myTasks: "مهامي",
  products: "المنتجات",
  inventory: "المخزون",
  orders: "الطلبات",
  customers: "العملاء",
  marketing: "التسويق",
  ai: "الذكاء الاصطناعي",
  settings: "الإعدادات",
  logout: "تسجيل الخروج",
  // topbar
  workspace: "مساحة العمل",
  switchWorkspace: "تبديل مساحة العمل",
  addWorkspace: "إضافة مساحة عمل",
  search: "بحث",
  searchPlaceholder: "ابحث أو انتقل إلى…",
  searchHint: "اضغط للتنقل السريع",
  create: "إنشاء",
  newOrder: "طلب جديد",
  newProduct: "منتج جديد",
  newCampaign: "حملة جديدة",
  newKnowledge: "إضافة معرفة",
  newInvitation: "دعوة عضو",
  goDashboard: "الذهاب إلى الرئيسية",
  goInbox: "الذهاب إلى المحادثات",
  goOrders: "الذهاب إلى الطلبات",
  goProducts: "الذهاب إلى المنتجات",
  goCustomers: "الذهاب إلى العملاء",
  goInventory: "الذهاب إلى المخزون",
  goMarketing: "الذهاب إلى التسويق",
  goAi: "الذهاب إلى الذكاء الاصطناعي",
  goSettings: "الذهاب إلى الإعدادات",
  navigation: "تنقل",
  quickActions: "إجراءات سريعة",
  noResultsFound: "لا توجد نتائج مطابقة",
  cmdKHint: "للتنقل السريع",
  // auth
  login: "تسجيل الدخول",
  register: "حساب جديد",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  fullName: "الاسم بالكامل",
  storeName: "اسم المتجر",
  // inbox
  conversations: "المحادثات",
  writeReply: "اكتب ردك…",
  send: "إرسال",
  noConversations: "لا توجد محادثات بعد",
  noConversationsHint: "عندما يراسلك عملاء من واتساب أو تليجرام ستظهر محادثاتهم هنا.",
  selectConversation: "اختر محادثة لعرضها",
  selectConversationHint: "كل المحادثات في مكان واحد — واتساب وتليجرام والويب تشات.",
  unread: "غير مقروءة",
  replyFailed: "تعذر إرسال الرد — حاول مرة تانية",
  // products
  addProduct: "إضافة منتج",
  productTitle: "اسم المنتج",
  price: "السعر",
  sku: "رمز SKU",
  status: "الحالة",
  active: "مفعّل",
  draft: "مسودة",
  archived: "مؤرشف",
  // inventory
  onHand: "الكمية المتاحة",
  reserved: "محجوز",
  warehouse: "المخزن",
  quantity: "الكمية",
  recordMovement: "تسجيل حركة",
  movementType: "نوع الحركة",
  in: "إضافة",
  out: "صرف",
  adjust: "تسوية",
  balances: "الأرصدة",
  movementsLog: "سجل الحركات",
  balanceAfter: "الرصيد بعد",
  reason: "السبب",
  noBalances: "لا توجد أرصدة بعد",
  noBalancesHint: "سجّل أول حركة مخزون لتظهر الأرصدة هنا.",
  noMovements: "لا توجد حركات بعد",
  noMovementsHint: "سجل حركات الإضافة والصرف لتتبع المخزون.",
  movementRecorded: "تم تسجيل الحركة",
  // orders
  createOrder: "إنشاء طلب",
  orderNumber: "رقم الطلب",
  grandTotal: "الإجمالي",
  customer: "العميل",
  lineItems: "أصناف الطلب",
  addLine: "+ سطر",
  chooseCustomer: "— اختر عميل —",
  chooseProduct: "— اختر منتج —",
  orderCreated: "تم إنشاء الطلب",
  orderCreatedHint: "أرسل تفاصيل الطلب للعميل من المحادثات.",
  noOrders: "لا توجد طلبات بعد",
  noOrdersHint: "أنشئ طلبًا يدويًا أو اجمع الطلبات تلقائيًا من المحادثات.",
  pending: "قيد الانتظار",
  confirmed: "مؤكد",
  processing: "قيد التجهيز",
  shipped: "تم الشحن",
  delivered: "تم التسليم",
  completed: "مكتمل",
  cancelled: "ملغي",
  refunded: "مسترد",
  // customers
  name: "الاسم",
  phone: "الهاتف",
  totalSpent: "إجمالي الشراء",
  searchCustomers: "بحث بالاسم أو الهاتف…",
  noCustomers: "لا يوجد عملاء بعد",
  noCustomersHint: "العملاء يظهرون تلقائيًا مع أول محادثة أو طلب.",
  // marketing
  newCampaignTitle: "حملة جديدة",
  campaignName: "الاسم",
  provider: "المنصة",
  budget: "الميزانية",
  campaigns: "الحملات",
  roas: "العائد على الإنفاق (ROAS)",
  spend: "الإنفاق",
  revenue: "الإيراد",
  noCampaigns: "لا توجد حملات بعد",
  noCampaignsHint: "أنشئ أول حملة لتتبع الإيراد والعائد لكل منصة.",
  noRoasData: "لا توجد بيانات عائد بعد",
  revenue30: "إيرادات 30 يوم",
  orders30: "الطلبات (30 يوم)",
  revenueBySource: "الإيرادات حسب المصدر",
  dailyRevenue: "الإيرادات اليومية (14 يوم)",
  noSourceData: "لا توجد تحويلات مرتبطة بمصادر",
  // ai
  knowledge: "قاعدة المعرفة",
  addKnowledge: "إضافة معرفة",
  searchKnowledge: "بحث في المعرفة",
  agents: "الوكلاء",
  usageCost: "الاستهلاك والتكلفة",
  totalTokens: "إجمالي التوكنات",
  aiTabKnowledge: "قاعدة المعرفة",
  aiTabSearch: "البحث الذكي",
  aiTabUsage: "الاستهلاك",
  askPlaceholder: "اكتب سؤالك…",
  ask: "بحث",
  noHits: "لا نتائج — جرّب صياغة تانية",
  knowledgeAdded: "تمت الإضافة إلى قاعدة المعرفة",
  indexed: "مفهرس",
  aiProcessing: "قيد المعالجة",
  knowledgeEmpty: "قاعدة المعرفة فارغة",
  knowledgeEmptyHint: "أضف أسئلة وأجوبة متكررة ليستخدمها الرد الذكي.",
  distance: "بعد",
  title: "العنوان",
  content: "المحتوى",
  // settings
  team: "الفريق",
  invite: "دعوة عضو",
  role: "الدور",
  owner: "المالك",
  manager: "مدير",
  staff: "موظف",
  integrations: "التكاملات",
  invitations: "الدعوات",
  channelProvider: "القناة / المزوّد",
  kind: "النوع",
  connected: "متصل",
  disconnected: "غير متصل",
  invitationCreated: "تم إنشاء الدعوة",
  invitationCreatedHint: "أرسل رابط القبول لعضو الفريق",
  acceptLink: "رابط القبول",
  pendingStatus: "قيد الانتظار",
  noInvitations: "لا توجد دعوات",
  noInvitationsHint: "ادعُ عضو فريق ليساعدك في إدارة المتجر.",
  noIntegrations: "لا توجد تكاملات بعد",
  noIntegrationsHint: "أضف قناة واتساب أو تليجرام لتبدأ استقبال المحادثات.",
  // tasks
  tasksEmpty: "لا توجد مهام بعد",
  tasksEmptyHint: "المهام المتعلقة بالعملاء والطلبات ستظهر هنا تلقائيًا.",
  // generic
  save: "حفظ",
  cancel: "إلغاء",
  loading: "جارٍ التحميل…",
  actions: "إجراءات",
  date: "التاريخ",
  total: "الإجمالي",
  retry: "حاول مرة تانية",
  somethingWentWrong: "حدث خطأ ما",
  rowsSelected: "محدد",
  rowsPerPage: "صفوف بالصفحة",
  pageOf: (page: number, total: number) => `صفحة ${page} من ${total}`,
  prevPage: "السابق",
  nextPage: "التالي",
  searchTable: "ابحث في الجدول…",
  noTableResults: "لا نتائج مطابقة",
  sortAsc: "تصاعدي",
  sortDesc: "تنازلي",
  selectRow: "تحديد الصف",
  selectAll: "تحديد الكل",
  lowStockAlert: (n: number) => `عندك ${n} صنف مخزونه على وشك النفاد — راجع صفحة المخزون.`,
  lowStock: "مخزون منخفض",
  lowStockHint: "راجع المخزون قبل النفاد",
  openConversations: "محادثات مفتوحة",
  activeProducts: "منتجات مفعّلة",
  aov: "متوسط قيمة الطلب",
  nearlyOut: (n: number) => `${n} منتج شبه نافد`,
} as const;


const en = {
  brand: "Sales OS",
  groupHome: "Home",
  groupWork: "Work",
  groupBusiness: "Business",
  groupGrowth: "Growth",
  groupAi: "AI",
  groupAdmin: "Admin",
  dashboard: "Home",
  inbox: "Inbox",
  myTasks: "My Tasks",
  products: "Products",
  inventory: "Inventory",
  orders: "Orders",
  customers: "Customers",
  marketing: "Marketing",
  ai: "AI",
  settings: "Settings",
  logout: "Sign out",
  login: "Sign in",
  register: "Create account",
  email: "Email",
  password: "Password",
  fullName: "Full name",
  storeName: "Store name",
  writeReply: "Write a reply…",
  send: "Send",
  noConversations: "No conversations yet",
  selectConversation: "Select a conversation",
  addProduct: "Add product",
  productTitle: "Product title",
  price: "Price",
  sku: "SKU",
  status: "Status",
  createOrder: "Create order",
  orderNumber: "Order no.",
  grandTotal: "Total",
  customer: "Customer",
  quantity: "Qty",
  warehouse: "Warehouse",
  onHand: "On hand",
  reserved: "Reserved",
  knowledge: "Knowledge",
  addKnowledge: "Add knowledge",
  searchKnowledge: "Search knowledge",
  agents: "Agents",
  usageCost: "Usage & cost",
  team: "Team",
  invite: "Invite member",
  role: "Role",
  owner: "Owner",
  manager: "Manager",
  staff: "Staff",
  integrations: "Integrations",
  save: "Save",
  cancel: "Cancel",
  loading: "Loading…",
  actions: "Actions",
  date: "Date",
  total: "Total",
  search: "Search",
  create: "Create",
  workspace: "Workspace",
  switchWorkspace: "Switch workspace",
  addWorkspace: "Add workspace",
  quickActions: "Quick actions",
  theme: "Theme",
  language: "Language",
} as const;



const dictionaries: Record<Lang, Record<string, unknown>> = {
  ar,
  en: en as unknown as Record<string, unknown>,
};

/** Language-aware vocabulary proxy — reads the active language at access
 * time, so a reload after setLang() re-renders everything in that language
 * while the layout direction stays exactly as-is. */
export const t = makeT(dictionaries) as typeof ar;

export const languages: { code: Lang; label: string }[] = [
  { code: "ar", label: "العربية" },
  { code: "en", label: "English" },
];
