/** Shared vocabulary — bilingual (ar default / en) via a language-aware
 * proxy. The LAYOUT never flips (direction stays RTL per directive); only
 * strings switch. Screens keep `import { t }` unchanged. */

import { makeT, type Lang } from "@/lib/i18n";
const ar = {
  brand: "FIHRIST",
  // nav groups (§89)
  groupHome: "الرئيسية",
  groupWork: "المحادثات",
  groupBusiness: "الأعمال",
  groupGrowth: "النمو",
  groupAi: "الذكاء الاصطناعي",
  groupAdmin: "الإدارة",
  groupAutomation: "الأتمتة",
  groupAnalytics: "التحليلات",
  groupOperations: "العمليات",
  automationFlows: "مسارات الأتمتة",
  n8nWorkflows: "مسارات n8n",
  dashboards: "لوحات البيانات",
  reports: "التقارير",
  health: "الصحة",
  auditLog: "سجل التدقيق",
  // nav items
  dashboard: "الرئيسية",
  inbox: "المحادثات",
  myTasks: "مهامي",
  products: "المنتجات",
  inventory: "المخزون",
  orders: "الطلبات",
  customers: "العملاء",
  marketing: "التسويق",
  ai: "الذكاء الاصطناعي",
  decisions: "سجل القرارات",
  effects: "التسوية والتأثيرات",
  financial: "الدفتر المالي",
  settings: "الإعدادات",
  logout: "تسجيل الخروج",
  // topbar
  workspace: "مساحة العمل",
  switchWorkspace: "تبديل مساحة العمل",
  addWorkspace: "إضافة مساحة عمل",
  search: "بحث",
  searchPlaceholder: "ابحث أو انتقل إلى…",
  searchHint: "اضغط للتنقل السريع",
  create: "إنشاء",
  newOrder: "طلب جديد",
  newProduct: "منتج جديد",
  newCampaign: "حملة جديدة",
  newKnowledge: "إضافة معرفة",
  newInvitation: "دعوة عضو",
  goDashboard: "الذهاب إلى الرئيسية",
  goInbox: "الذهاب إلى المحادثات",
  goOrders: "الذهاب إلى الطلبات",
  goProducts: "الذهاب إلى المنتجات",
  goCustomers: "الذهاب إلى العملاء",
  goInventory: "الذهاب إلى المخزون",
  goMarketing: "الذهاب إلى التسويق",
  goAi: "الذهاب إلى الذكاء الاصطناعي",
  goSettings: "الذهاب إلى الإعدادات",
  navigation: "تنقل",
  quickActions: "إجراءات سريعة",
  noResultsFound: "لا توجد نتائج مطابقة",
  cmdKHint: "للتنقل السريع",
  // auth
  login: "تسجيل الدخول",
  register: "حساب جديد",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  fullName: "الاسم بالكامل",
  storeName: "اسم المتجر",
  // inbox
  conversations: "المحادثات",
  writeReply: "اكتب ردك…",
  send: "إرسال",
  noConversations: "لا توجد محادثات بعد",
  noConversationsHint: "عندما يراسلك عملاء من واتساب أو تليجرام ستظهر محادثاتهم هنا.",
  selectConversation: "اختر محادثة لعرضها",
  selectConversationHint: "كل المحادثات في مكان واحد — واتساب وتليجرام والويب تشات.",
  unread: "غير مقروءة",
  replyFailed: "تعذر إرسال الرد — حاول مرة تانية",
  // inbox §99 — views rail
  viewMy: "صندوقي",
  viewUnassigned: "غير مُعيَّنة",
  viewPriority: "الأولوية",
  viewSlaRisk: "خطر الوقت",
  viewWaitingCustomer: "بانتظار العميل",
  viewWaitingTeam: "بانتظار الفريق",
  viewVip: "عملاء مميزون",
  viewAi: "معالجة AI",
  viewAiHandover: "تحويل من AI",
  viewMentioned: "ذُكرت فيها",
  viewTeam: "الفريق",
  viewCustom: "مخصصة",
  comingSoon: "قريبًا",
  allChannels: "القنوات",
  inboxFilteredLocalHint: "تُصفّى من الصفحات المحمّلة حاليًا",
  // inbox §99 — context panel tabs
  ctxCustomer: "العميل",
  ctxOrders: "الطلبات",
  ctxTimeline: "الجدول الزمني",
  ctxAi: "الذكاء",
  ctxNotes: "ملاحظات",
  // inbox §99 — assign
  assign: "تعيين",
  assignedToYou: "مُعيَّنة لك",
  assignToMe: "تعيين لنفسي",
  unassign: "إزالة التعيين",
  assignOtherMember: "اختيار عضو آخر…",
  assignedBadge: "مُعيَّنة",
  // products
  addProduct: "إضافة منتج",
  productTitle: "اسم المنتج",
  price: "السعر",
  sku: "رمز SKU",
  status: "الحالة",
  active: "مفعّل",
  draft: "مسودة",
  archived: "مؤرشف",
  // inventory
  onHand: "الكمية المتاحة",
  reserved: "محجوز",
  warehouse: "المخزن",
  quantity: "الكمية",
  recordMovement: "تسجيل حركة",
  movementType: "نوع الحركة",
  in: "إضافة",
  out: "صرف",
  adjust: "تسوية",
  balances: "الأرصدة",
  movementsLog: "سجل الحركات",
  balanceAfter: "الرصيد بعد",
  reason: "السبب",
  noBalances: "لا توجد أرصدة بعد",
  noBalancesHint: "سجّل أول حركة مخزون لتظهر الأرصدة هنا.",
  noMovements: "لا توجد حركات بعد",
  noMovementsHint: "سجل حركات الإضافة والصرف لتتبع المخزون.",
  movementRecorded: "تم تسجيل الحركة",
  // orders
  createOrder: "إنشاء طلب",
  orderNumber: "رقم الطلب",
  grandTotal: "الإجمالي",
  customer: "العميل",
  lineItems: "أصناف الطلب",
  addLine: "+ سطر",
  chooseCustomer: "— اختر عميل —",
  chooseProduct: "— اختر منتج —",
  orderCreated: "تم إنشاء الطلب",
  orderCreatedHint: "أرسل تفاصيل الطلب للعميل من المحادثات.",
  undo: "تراجع",
  orderCancelled: "تم إلغاء الطلب",
  undoFailed: "تعذّر التراجع",
  noOrders: "لا توجد طلبات بعد",
  noOrdersHint: "أنشئ طلبًا يدويًا أو اجمع الطلبات تلقائيًا من المحادثات.",
  pending: "قيد الانتظار",
  confirmed: "مؤكد",
  processing: "قيد التجهيز",
  shipped: "تم الشحن",
  delivered: "تم التسليم",
  completed: "مكتمل",
  cancelled: "ملغي",
  refunded: "مسترد",
  // customers
  name: "الاسم",
  phone: "الهاتف",
  totalSpent: "إجمالي الشراء",
  searchCustomers: "بحث بالاسم أو الهاتف…",
  noCustomers: "لا يوجد عملاء بعد",
  noCustomersHint: "العملاء يظهرون تلقائيًا مع أول محادثة أو طلب.",
  // marketing
  newCampaignTitle: "حملة جديدة",
  campaignName: "الاسم",
  provider: "المنصة",
  budget: "الميزانية",
  campaigns: "الحملات",
  roas: "العائد على الإنفاق (ROAS)",
  spend: "الإنفاق",
  revenue: "الإيراد",
  /** ADR-053: شاشات الفلوس ما بقاش فيها رقم اسمه "الإيرادات" بس. الإجمالي
   *  (قبل الاسترداد) والصافي (بعده) رقمين مختلفين، واللازم يوضح أيهم. */
  grossRevenue30: "إجمالي الإيرادات (30 يوم)",
  netRevenue30: "صافي الإيرادات (30 يوم)",
  refunded30: "المسترد (30 يوم)",
  grossShort: "الإجمالي",
  netShort: "الصافي",
  refundedShort: "المسترد",
  grossAov: "متوسط قيمة الطلب (إجمالي)",
  netAov: "متوسط قيمة الطلب (صافٍ)",
  /** الصافي مقفول عند صفر: لو المرتجعات أكبر من المحصَّل في الفترة، الفرق
   *  بيظهر كـ refund_excess بدل ما يختفي — لازم الشاشة تقول كده. */
  refundExcessNote: (amount: string) =>
    `المرتجعات تجاوزت المحصَّل في الفترة: ${amount} ما اتخصمش من الصافي ده.`,
  /** §167: `revenue_by_source`/`revenue_by_campaign` هم قيمة الإسناد باللمسة
   *  الأخيرة، مش فلوس اتقبضت — تسميتهم "منسوب" مش اختيارية. */
  attributedRevenue: "إيراد منسوب",
  attributedCreditHint:
    "الإيراد المنسوب = قيمة التحويلات المسندة باللمسة الأخيرة، وهو مش بالضرورة مال متحصيل.",
  campaignReturn: "عائد كل حملة",
  noSpendFeed: "لا يوجد مصدر صرف",
  noPlannedBudget: "لا ميزانية مخططة",
  /** الأساس اللي اتقسمت عليه النسبة: planned_budget النهارده، أو الصرف الفعلي
   *  لما يبقى له مصدر. */
  basisPlannedBudget: "على الميزانية المخططة",
  basisActualSpend: "على الصرف الفعلي",
  noCampaigns: "لا توجد حملات بعد",
  noCampaignsHint: "أنشئ أول حملة لتتبع الإيراد المنسوب والعائد لكل منصة.",
  noRoasData: "لا توجد بيانات عائد بعد",
  /** §167: a metric must carry its own denominator. The dashboard shows the
   *  ratio the backend actually produced — the label has to match. */
  budgetRoasLabel: "العائد على الميزانية المخططة",
  spendRoasLabel: "العائد على الإنفاق (ROAS)",
  returnRatioCol: "العائد (نسبة)",
  plannedBudgetCol: "الميزانية المخططة",
  actualSpendCol: "الصرف الفعلي",
  revenue30: "إيرادات 30 يوم",
  orders30: "الطلبات (30 يوم)",
  revenueBySource: "إيراد منسوب حسب المصدر",
  dailyNetRevenue: "صافي الإيرادات اليومية (14 يوم)",
  noSourceData: "لا توجد تحويلات مرتبطة بمصادر",
  // ai
  knowledge: "قاعدة المعرفة",
  addKnowledge: "إضافة معرفة",
  searchKnowledge: "بحث في المعرفة",
  agents: "الوكلاء",
  usageCost: "الاستهلاك والتكلفة",
  totalTokens: "إجمالي التوكنات",
  aiTabKnowledge: "قاعدة المعرفة",
  aiTabSearch: "البحث الذكي",
  aiTabUsage: "الاستهلاك",
  askPlaceholder: "اكتب سؤالك…",
  ask: "بحث",
  noHits: "لا نتائج — جرّب صياغة تانية",
  knowledgeAdded: "تمت الإضافة إلى قاعدة المعرفة",
  indexed: "مفهرس",
  aiProcessing: "قيد المعالجة",
  knowledgeEmpty: "قاعدة المعرفة فارغة",
  knowledgeEmptyHint: "أضف أسئلة وأجوبة متكررة ليستخدمها الرد الذكي.",
  distance: "بعد",
  title: "العنوان",
  content: "المحتوى",
  // settings
  team: "الفريق",
  invite: "دعوة عضو",
  role: "الدور",
  owner: "المالك",
  manager: "مدير",
  staff: "موظف",
  integrations: "التكاملات",
  invitations: "الدعوات",
  channelProvider: "القناة / المزوّد",
  kind: "النوع",
  connected: "متصل",
  disconnected: "غير متصل",
  invitationCreated: "تم إنشاء الدعوة",
  invitationCreatedHint: "أرسل رابط القبول لعضو الفريق",
  acceptLink: "رابط القبول",
  pendingStatus: "قيد الانتظار",
  revoke: "إلغاء",
  invitationRevoked: "تم إلغاء الدعوة",
  noInvitations: "لا توجد دعوات",
  noInvitationsHint: "ادعُ عضو فريق ليساعدك في إدارة المتجر.",
  noIntegrations: "لا توجد تكاملات بعد",
  noIntegrationsHint: "أضف قناة واتساب أو تليجرام لتبدأ استقبال المحادثات.",
  // tasks
  tasksEmpty: "لا توجد مهام بعد",
  tasksEmptyHint: "المهام المتعلقة بالعملاء والطلبات ستظهر هنا تلقائيًا.",
  newTask: "مهمة جديدة",
  taskTitle: "عنوان المهمة",
  taskDescription: "تفاصيل المهمة",
  taskPriority: "الأولوية",
  taskCreated: "تم إنشاء المهمة",
  taskCreate: "إنشاء المهمة",
  taskAll: "الكل",
  taskTodo: "لم تبدأ",
  taskInProgress: "جارية",
  taskDone: "مكتملة",
  taskCancelled: "ملغاة",
  taskMarkDone: "تحديد كمكتملة",
  taskReopen: "إعادة فتح",
  // my work (§97)
  myWork: "شغلي",
  myWorkDescription: "كل اللي محتاج تعمله دلوقتي في مكان واحد.",
  slaRisk: "خطر تجاوز الوقت",
  slaRiskHint: "محادثات قربت تتجاوز مدة الرد المتفق عليها.",
  slaRiskEmpty: "مفيش محادثات في خطر دلوقتي",
  slaRiskEmptyHint: "كل المحادثات داخل المدة المتفق عليها.",
  slaAtRisk: "في خطر",
  slaBreached: "متأخر",
  slaMinutesLeft: (n: number) => `${n} دقيقة`,
  slaHoursLeft: (n: number) => `${n} ساعة`,
  slaOverdueMinutes: (n: number) => `متأخر ${n} دقيقة`,
  slaOverdueHours: (n: number) => `متأخر ${n} ساعات`,
  myApprovals: "موافقاتي",
  myApprovalsHint: "إجراءات عالية الخطورة محتاجة قرارك.",
  myApprovalsEmpty: "مفيش موافقات معلقة",
  myApprovalsEmptyHint: "كل الإجراءات المحتاجة موافقة تم البت فيها.",
  approvalRisk: "مستوى الخطورة",
  approvalExpires: "تنتهي",
  approvalNoExpiry: "بدون وقت انتهاء",
  riskHigh: "عالية",
  riskLow: "منخفضة",
  approvalsTitle: "الموافقات",
  approvalsSubtitle: "إجراءات AI عالية المخاطر بانتظار قرار",
  approvalsPending: "بانتظار القرار",
  approvalsResolved: "المحظورة",
  approvalsEmpty: "لا توجد موافقات",
  approvalsEmptyHint: "لم يتم رصد أي إجراءات عالية المخاطر بانتظار قرار",
  approvalsApprove: "موافقة",
  approvalsReject: "رفض",
  myAssignedTasks: "مهامي الموكلة",
  myAssignedTasksHint: "مهام معيّنة لك.",
  myAssignedTasksEmpty: "مفيش مهام موكلة لك",
  myAssignedTasksEmptyHint: "المهام المعيّنة لك هتظهر هنا.",
  myAssignedConversations: "محادثاتي",
  myAssignedConversationsHint: "محادثات مسندة لك.",
  myAssignedConversationsEmpty: "مفيش محادثات مسندة لك",
  myAssignedConversationsEmptyHint: "المحادثات المسندة لك هتظهر هنا.",
  dueDate: "تاريخ الاستحقاق",
  // health indicator (§103)
  healthLabel: "حالة النظام",
  healthHealthy: "كل الأنظمة تعمل",
  healthDegraded: "أداء متدهور",
  healthDown: "خلل في النظام",
  healthUnknown: "حالة غير معروفة",
  healthOk: "سليم",
  healthSubsystems: "الأنظمة الفرعية",
  healthIssues: (n: number) => `${n} مشكلة`,
  healthDatabase: "قاعدة البيانات",
  healthRedis: "التخزين المؤقت",
  healthOutbox: "طابور الأحداث",
  healthDlq: "الرسائل الميتة",
  healthIntegrations: "التكاملات",
  // generic
  save: "حفظ",
  cancel: "إلغاء",
  loading: "جارٍ التحميل…",
  loadMore: "تحميل المزيد",
  actions: "إجراءات",
  date: "التاريخ",
  total: "الإجمالي",
  retry: "حاول مرة تانية",
  somethingWentWrong: "حدث خطأ ما",
  rowsSelected: "محدد",
  rowsPerPage: "صفوف بالصفحة",
  pageOf: (page: number, total: number) => `صفحة ${page} من ${total}`,
  prevPage: "السابق",
  nextPage: "التالي",
  searchTable: "ابحث في الجدول…",
  noTableResults: "لا نتائج مطابقة",
  sortAsc: "تصاعدي",
  sortDesc: "تنازلي",
  selectRow: "تحديد الصف",
  selectAll: "تحديد الكل",
  lowStockAlert: (n: number) => `عندك ${n} صنف مخزونه على وشك النفاد — راجع صفحة المخزون.`,
  /** M7: رف فاضي مش "مخزون منخفض". الشريطين اتفصلوا عشان التنبيه يفضل قابل
   *  للتنفيذ، والصنف اللي خلص ليه كلمة لوحده. */
  outOfStockAlert: (n: number) => `عندك ${n} صنف خلص من المخزون — راجع صفحة المخزون.`,
  soldOutCount: (n: number) => `${n} صنف نفد من المخزون`,
  lowStockThresholdNote: (n: number) => `الحد: ${n} وحدة أو أقل`,
  lowStock: "مخزون منخفض",
  lowStockHint: "راجع المخزون قبل النفاد",
  openConversations: "محادثات مفتوحة",
  activeProducts: "منتجات مفعّلة",
  aov: "متوسط قيمة الطلب",
  nearlyOut: (n: number) => `${n} منتج شبه نافد`,
  needsAttention: "يحتاج انتباهك",
  allClear: "مفيش إجراءات عاجلة دلوقتي",
  today: "النهارده",
  searchResults: "نتائج من النظام",
  searching: "جاري البحث…",

  // Customer 360 record (spec W5)
  customer360: "ملف العميل",
  customer360Description: "كل حاجة عن العميل في مكان واحد: الطلبات، المحادثات، المهام، والمدفوعات.",
  backToCustomers: "رجوع للعملاء",
  customerNotFound: "العميل غير موجود",
  customerNotFoundHint: "يمكن يكون اتحذف أو مش تابع لحسابك.",
  c360Overview: "نظرة عامة",
  c360Orders: "الطلبات",
  c360Conversations: "المحادثات",
  c360Tasks: "المهام",
  c360Timeline: "الخط الزمني",
  c360Identity: "الهوية والاتصال",
  c360Contact: "بيانات الاتصال",
  c360LifetimeValue: "إجمالي المشتريات",
  c360OrdersCount: "عدد الطلبات",
  c360OrdersValue: "قيمة الطلبات",
  c360Paid: "المحصّل",
  c360Refunded: "المرتجع",
  c360NetCollected: "الصافي المحصّل",
  c360Outstanding: "المتبقي",
  c360PaymentsCount: "عدد الدفعات",
  c360OpenTasks: "مهام مفتوحة",
  c360Unread: "رسائل غير مقروءة",
  c360LastOrder: "آخر طلب",
  c360LastMessage: "آخر رسالة",
  c360Identities: "حسابات القنوات",
  c360IdentitiesEmpty: "مفيش حسابات قنوات مربوطة",
  c360Addresses: "العناوين",
  c360AddressesEmpty: "مفيش عناوين مسجلة",
  c360Notes: "ملاحظات",
  c360NotesEmpty: "مفيش ملاحظات",
  c360Tags: "الوسوم",
  c360TagsEmpty: "مفيش وسوم",
  c360TimelineEmpty: "مفيش نشاط مسجّل",
  c360OrdersEmpty: "مفيش طلبات لهذا العميل",
  c360OrdersEmptyHint: "لما العميل يعمل أول طلب هيتسجّل هنا.",
  c360ConversationsEmpty: "مفيش محادثات",
  c360ConversationsEmptyHint: "أول رسالة من العميل هتظهر هنا.",
  c360TasksEmpty: "مفيش مهام مرتبطة بالعميل",
  c360TimelineEvent: "حدث",
  c360TimelineOrder: "طلب",
  c360TimelineConversation: "محادثة",
  c360TimelineNote: "ملاحظة",
  c360TimelineTask: "مهمة",
  c360OpenConversation: "افتح المحادثة",
  c360NewOrder: "طلب جديد",
  c360CustomerSince: "عميل من",
  c360Default: "افتراضي",
  c360Blocked: "محظور",
  c360Active: "نشط",
  viewAll: "عرض الكل",

  // Notifications centre (spec W5)
  notifications: "الإشعارات",
  notificationsHint: "كل التنبيهات اللي وصلتك، مقسّمة حسب النوع",
  markAllRead: "تحديد الكل كمقروء",
  markAsRead: "تحديد كمقروء",
  markSelectedRead: "تحديد المحدد كمقروء",
  noNotifications: "مفيش إشعارات",
  noNotificationsHint: "لما يحصل حاجة محتاجة انتباهك هتلاقيها هنا.",
  filterAll: "الكل",
  filterUnread: "غير المقروء",
  filterByKind: "حسب النوع",
  selectedCount: (n: number) => `${n} محدد`,
  allCaughtUp: "مفيش جديد",
  notificationsAllRead: "كل الإشعارات اتقرت",
  toOpen: "للفتح",

  // §104 — تأكيد الإجراءات الخطرة
  confirm: "تأكيد",
  confirmDescription: "هل أنت متأكد من تنفيذ هذا الإجراء؟ لا يمكن التراجع عنه.",
  revokeConfirmTitle: "إلغاء الدعوة؟",
  revokeConfirmBody: "سيتم إلغاء الدعوة ولن يستطيع صاحبها قبولها بعد كده. لا يمكن التراجع.",
  revokeConfirmAction: "إلغاء الدعوة",
  logoutConfirmTitle: "تسجيل الخروج؟",
  logoutConfirmBody: "هتحتاج تسجّل الدخول تاني للوصول إلى حسابك.",
  deleteViewConfirmTitle: "حذف العرض المحفوظ؟",
  deleteViewConfirmBody: (name: string) => `سيتم حذف العرض «${name}» نهائيًا. لا يمكن التراجع.`,
  deleteViewConfirmAction: "حذف العرض",
  approveConfirmTitle: "الموافقة على الإجراء؟",
  approveConfirmBody: "سيتم تنفيذ إجراء الذكاء الاصطناعي عالي المخاطرة فورًا بعد موافقتك — راجع التفاصيل كويس.",
  rejectConfirmTitle: "رفض الإجراء؟",
  rejectConfirmBody: "سيتم رفض الطلب وإنهاؤه. لا يمكن التراجع.",
  rejectConfirmAction: "تأكيد الرفض",

  // §97 — عروضي المحفوظة في «شغلي»
  mySavedViews: "عروضي المحفوظة",
  mySavedViewsHint: "اختصارات لعروض الفلاتر اللي حفظتها.",
  mySavedViewsEmpty: "مفيش عروض محفوظة",
  mySavedViewsEmptyHint: "احفظ عرض من صفحة العملاء أو الطلبات وسيظهر اختصار له هنا.",
} as const;


const en = {
  brand: "FIHRIST",
  // nav groups (§89)
  groupHome: "Home",
  groupWork: "Conversations",
  groupBusiness: "Business",
  groupGrowth: "Growth",
  groupAi: "AI",
  groupAdmin: "Admin",
  groupAutomation: "Automation",
  groupAnalytics: "Analytics",
  groupOperations: "Operations",
  automationFlows: "Automation Flows",
  n8nWorkflows: "n8n Workflows",
  dashboards: "Dashboards",
  reports: "Reports",
  health: "Health",
  auditLog: "Audit Log",
  // nav items
  dashboard: "Home",
  inbox: "Conversations",
  myTasks: "My tasks",
  products: "Products",
  inventory: "Inventory",
  orders: "Orders",
  customers: "Customers",
  marketing: "Marketing",
  ai: "AI",
  decisions: "Decisions",
  effects: "Effects Ledger",
  financial: "Financial Ledger",
  settings: "Settings",
  logout: "Sign out",
  // topbar
  workspace: "Workspace",
  switchWorkspace: "Switch workspace",
  addWorkspace: "Add workspace",
  search: "Search",
  searchPlaceholder: "Search or jump to…",
  searchHint: "Press for quick navigation",
  create: "Create",
  newOrder: "New order",
  newProduct: "New product",
  newCampaign: "New campaign",
  newKnowledge: "Add knowledge",
  newInvitation: "Invite member",
  goDashboard: "Go to home",
  goInbox: "Go to conversations",
  goOrders: "Go to orders",
  goProducts: "Go to products",
  goCustomers: "Go to customers",
  goInventory: "Go to inventory",
  goMarketing: "Go to marketing",
  goAi: "Go to AI",
  goSettings: "Go to settings",
  navigation: "Navigation",
  quickActions: "Quick actions",
  noResultsFound: "No matching results",
  cmdKHint: "for quick navigation",
  // auth
  login: "Sign in",
  register: "Create account",
  email: "Email",
  password: "Password",
  fullName: "Full name",
  storeName: "Store name",
  // inbox
  conversations: "Conversations",
  writeReply: "Write a reply…",
  send: "Send",
  noConversations: "No conversations yet",
  noConversationsHint: "When customers message you on WhatsApp or Telegram, their conversations will appear here.",
  selectConversation: "Select a conversation",
  selectConversationHint: "All conversations in one place — WhatsApp, Telegram and web chat.",
  unread: "Unread",
  replyFailed: "Couldn't send the reply — please try again",
  // inbox §99 — views rail
  viewMy: "My inbox",
  viewUnassigned: "Unassigned",
  viewPriority: "Priority",
  viewSlaRisk: "SLA risk",
  viewWaitingCustomer: "Waiting customer",
  viewWaitingTeam: "Waiting team",
  viewVip: "VIP",
  viewAi: "AI handling",
  viewAiHandover: "AI handover",
  viewMentioned: "Mentioned",
  viewTeam: "Team",
  viewCustom: "Custom",
  comingSoon: "Coming soon",
  allChannels: "Channels",
  inboxFilteredLocalHint: "Filtered over the currently loaded pages",
  // inbox §99 — context panel tabs
  ctxCustomer: "Customer",
  ctxOrders: "Orders",
  ctxTimeline: "Timeline",
  ctxAi: "AI",
  ctxNotes: "Notes",
  // inbox §99 — assign
  assign: "Assign",
  assignedToYou: "Assigned to you",
  assignToMe: "Assign to me",
  unassign: "Unassign",
  assignOtherMember: "Pick another member…",
  assignedBadge: "Assigned",
  // products
  addProduct: "Add product",
  productTitle: "Product title",
  price: "Price",
  sku: "SKU",
  status: "Status",
  active: "Active",
  draft: "Draft",
  archived: "Archived",
  // inventory
  onHand: "On hand",
  reserved: "Reserved",
  warehouse: "Warehouse",
  quantity: "Qty",
  recordMovement: "Record movement",
  movementType: "Movement type",
  in: "In",
  out: "Out",
  adjust: "Adjust",
  balances: "Balances",
  movementsLog: "Movements log",
  balanceAfter: "Balance after",
  reason: "Reason",
  noBalances: "No balances yet",
  noBalancesHint: "Record your first stock movement to see balances here.",
  noMovements: "No movements yet",
  noMovementsHint: "Record inbound and outbound movements to track inventory.",
  movementRecorded: "Movement recorded",
  // orders
  createOrder: "Create order",
  orderNumber: "Order no.",
  grandTotal: "Total",
  customer: "Customer",
  lineItems: "Line items",
  addLine: "+ Line",
  chooseCustomer: "— Select customer —",
  chooseProduct: "— Select product —",
  orderCreated: "Order created",
  orderCreatedHint: "Send the order details to the customer from the inbox.",
  undo: "Undo",
  orderCancelled: "Order cancelled",
  undoFailed: "Undo failed",
  noOrders: "No orders yet",
  noOrdersHint: "Create an order manually or collect orders automatically from conversations.",
  pending: "Pending",
  confirmed: "Confirmed",
  processing: "Processing",
  shipped: "Shipped",
  delivered: "Delivered",
  completed: "Completed",
  cancelled: "Cancelled",
  refunded: "Refunded",
  // customers
  name: "Name",
  phone: "Phone",
  totalSpent: "Total spent",
  searchCustomers: "Search by name or phone…",
  noCustomers: "No customers yet",
  noCustomersHint: "Customers appear automatically with the first conversation or order.",
  // marketing
  newCampaignTitle: "New campaign",
  campaignName: "Name",
  provider: "Provider",
  budget: "Budget",
  campaigns: "Campaigns",
  roas: "Return on ad spend (ROAS)",
  spend: "Spend",
  revenue: "Revenue",
  /** ADR-053: money screens no longer show one number called "revenue" —
   *  gross (before refunds) and net (after) are different figures, and the
   *  label has to say which one it is. */
  grossRevenue30: "Gross revenue (30 days)",
  netRevenue30: "Net revenue (30 days)",
  refunded30: "Refunded (30 days)",
  grossShort: "Gross",
  netShort: "Net",
  refundedShort: "Refunded",
  grossAov: "Average order value (gross)",
  netAov: "Average order value (net)",
  /** Net is floored at zero: when refunds beat collections in the window the
   *  remainder ships as refund_excess instead of vanishing, and the screen
   *  has to say so. */
  refundExcessNote: (amount: string) =>
    `Refunds exceeded collections in this window: ${amount} was not subtracted from this net.`,
  /** §167: revenue_by_source / revenue_by_campaign are last-touch attributed
   *  credit, not collected money — calling them "attributed" is mandatory. */
  attributedRevenue: "Attributed revenue",
  attributedCreditHint:
    "Attributed revenue is the conversion value credited to the last touchpoint; it is not necessarily money collected.",
  campaignReturn: "Return per campaign",
  noSpendFeed: "No spend feed",
  noPlannedBudget: "No planned budget",
  noCampaigns: "No campaigns yet",
  noCampaignsHint: "Create your first campaign to track attributed revenue and return per channel.",
  noRoasData: "No ROAS data yet",
  budgetRoasLabel: "Return on planned budget",
  spendRoasLabel: "Return on ad spend (ROAS)",
  returnRatioCol: "Return (ratio)",
  plannedBudgetCol: "Planned budget",
  actualSpendCol: "Actual spend",
  revenue30: "30-day revenue",
  orders30: "Orders (30 days)",
  revenueBySource: "Attributed revenue by source",
  dailyNetRevenue: "Daily net revenue (14 days)",
  noSourceData: "No conversions linked to sources",
  // ai
  knowledge: "Knowledge base",
  addKnowledge: "Add knowledge",
  searchKnowledge: "Search knowledge",
  agents: "Agents",
  usageCost: "Usage & cost",
  totalTokens: "Total tokens",
  aiTabKnowledge: "Knowledge base",
  aiTabSearch: "Smart search",
  aiTabUsage: "Usage",
  askPlaceholder: "Type your question…",
  ask: "Search",
  noHits: "No results — try a different phrasing",
  knowledgeAdded: "Added to the knowledge base",
  indexed: "Indexed",
  aiProcessing: "Processing",
  knowledgeEmpty: "The knowledge base is empty",
  knowledgeEmptyHint: "Add frequently asked questions and answers for the smart reply to use.",
  distance: "Distance",
  title: "Title",
  content: "Content",
  // settings
  team: "Team",
  invite: "Invite member",
  role: "Role",
  owner: "Owner",
  manager: "Manager",
  staff: "Staff",
  integrations: "Integrations",
  invitations: "Invitations",
  channelProvider: "Channel / provider",
  kind: "Type",
  connected: "Connected",
  disconnected: "Disconnected",
  invitationCreated: "Invitation created",
  invitationCreatedHint: "Send the accept link to your teammate",
  acceptLink: "Accept link",
  pendingStatus: "Pending",
  revoke: "Revoke",
  invitationRevoked: "Invitation revoked",
  noInvitations: "No invitations",
  noInvitationsHint: "Invite a teammate to help you manage the store.",
  noIntegrations: "No integrations yet",
  noIntegrationsHint: "Add a WhatsApp or Telegram channel to start receiving conversations.",
  // tasks
  tasksEmpty: "No tasks yet",
  tasksEmptyHint: "Tasks related to customers and orders will appear here automatically.",
  newTask: "New task",
  taskTitle: "Task title",
  taskDescription: "Task details",
  taskPriority: "Priority",
  taskCreated: "Task created",
  taskCreate: "Create task",
  taskAll: "All",
  taskTodo: "To do",
  taskInProgress: "In progress",
  taskDone: "Done",
  taskCancelled: "Cancelled",
  taskMarkDone: "Mark as done",
  taskReopen: "Reopen",
  // my work (§97)
  myWork: "My work",
  myWorkDescription: "Everything you need to do right now, in one place.",
  slaRisk: "SLA risk",
  slaRiskHint: "Conversations close to breaching their agreed response time.",
  slaRiskEmpty: "No conversations at risk",
  slaRiskEmptyHint: "Every conversation is within its SLA.",
  slaAtRisk: "At risk",
  slaBreached: "Overdue",
  slaMinutesLeft: (n: number) => `${n} min`,
  slaHoursLeft: (n: number) => `${n} h`,
  slaOverdueMinutes: (n: number) => `Overdue ${n} min`,
  slaOverdueHours: (n: number) => `Overdue ${n} h`,
  myApprovals: "My approvals",
  myApprovalsHint: "High-risk actions waiting for your decision.",
  myApprovalsEmpty: "No pending approvals",
  myApprovalsEmptyHint: "Every action that needed approval has been decided.",
  approvalRisk: "Risk level",
  approvalExpires: "Expires",
  approvalNoExpiry: "No expiry",
  riskHigh: "High",
  riskLow: "Low",
  approvalsTitle: "Approvals",
  approvalsSubtitle: "High-risk AI actions awaiting your decision",
  approvalsPending: "Pending decision",
  approvalsResolved: "Resolved",
  approvalsEmpty: "No approvals",
  approvalsEmptyHint: "No high-risk actions are waiting for a decision",
  approvalsApprove: "Approve",
  approvalsReject: "Reject",
  myAssignedTasks: "My assigned tasks",
  myAssignedTasksHint: "Tasks assigned to you.",
  myAssignedTasksEmpty: "No tasks assigned to you",
  myAssignedTasksEmptyHint: "Tasks assigned to you will appear here.",
  myAssignedConversations: "My conversations",
  myAssignedConversationsHint: "Conversations assigned to you.",
  myAssignedConversationsEmpty: "No conversations assigned to you",
  myAssignedConversationsEmptyHint: "Conversations assigned to you will appear here.",
  dueDate: "Due date",
  // health indicator (§103)
  healthLabel: "System health",
  healthHealthy: "All systems operational",
  healthDegraded: "Degraded performance",
  healthDown: "System outage",
  healthUnknown: "Health unknown",
  healthOk: "OK",
  healthSubsystems: "Subsystems",
  healthIssues: (n: number) => `${n} issue(s)`,
  healthDatabase: "Database",
  healthRedis: "Cache",
  healthOutbox: "Event outbox",
  healthDlq: "Dead-letter queue",
  healthIntegrations: "Integrations",
  // generic
  save: "Save",
  cancel: "Cancel",
  loading: "Loading…",
  loadMore: "Load more",
  actions: "Actions",
  date: "Date",
  total: "Total",
  retry: "Try again",
  somethingWentWrong: "Something went wrong",
  rowsSelected: "selected",
  rowsPerPage: "Rows per page",
  pageOf: (page: number, total: number) => `Page ${page} of ${total}`,
  prevPage: "Previous",
  nextPage: "Next",
  searchTable: "Search the table…",
  noTableResults: "No matching results",
  sortAsc: "Ascending",
  sortDesc: "Descending",
  selectRow: "Select row",
  selectAll: "Select all",
  lowStockAlert: (n: number) => `You have ${n} item(s) running low — check the inventory page.`,
  /** M7: an empty shelf is not "low stock". The two bands split so the alert
   *  stays actionable and a sold-out item gets its own words. */
  outOfStockAlert: (n: number) => `You have ${n} item(s) sold out — check the inventory page.`,
  soldOutCount: (n: number) => `${n} item(s) sold out`,
  lowStockThresholdNote: (n: number) => `Threshold: ${n} unit(s) or fewer`,
  lowStock: "Low stock",
  lowStockHint: "Review stock before it runs out",
  openConversations: "Open conversations",
  activeProducts: "Active products",
  aov: "Average order value",
  nearlyOut: (n: number) => `${n} product(s) nearly out of stock`,
  needsAttention: "Needs attention",
  allClear: "Nothing urgent right now",
  today: "Today",
  searchResults: "Results from your system",
  searching: "Searching…",

  // Customer 360 record (spec W5)
  customer360: "Customer record",
  customer360Description: "Everything about this customer in one place: orders, conversations, tasks and payments.",
  backToCustomers: "Back to customers",
  customerNotFound: "Customer not found",
  customerNotFoundHint: "It may have been deleted, or it belongs to another account.",
  c360Overview: "Overview",
  c360Orders: "Orders",
  c360Conversations: "Conversations",
  c360Tasks: "Tasks",
  c360Timeline: "Timeline",
  c360Identity: "Identity & contact",
  c360Contact: "Contact details",
  c360LifetimeValue: "Lifetime value",
  c360OrdersCount: "Orders",
  c360OrdersValue: "Orders value",
  c360Paid: "Collected",
  c360Refunded: "Refunded",
  c360NetCollected: "Net collected",
  c360Outstanding: "Outstanding",
  c360PaymentsCount: "Payments",
  c360OpenTasks: "Open tasks",
  c360Unread: "Unread messages",
  c360LastOrder: "Last order",
  c360LastMessage: "Last message",
  c360Identities: "Channel accounts",
  c360IdentitiesEmpty: "No channel accounts linked",
  c360Addresses: "Addresses",
  c360AddressesEmpty: "No addresses on file",
  c360Notes: "Notes",
  c360NotesEmpty: "No notes",
  c360Tags: "Tags",
  c360TagsEmpty: "No tags",
  c360TimelineEmpty: "No recorded activity",
  c360OrdersEmpty: "No orders for this customer",
  c360OrdersEmptyHint: "Their first order will show up here.",
  c360ConversationsEmpty: "No conversations",
  c360ConversationsEmptyHint: "The first message from this customer will appear here.",
  c360TasksEmpty: "No tasks linked to this customer",
  c360TimelineEvent: "Event",
  c360TimelineOrder: "Order",
  c360TimelineConversation: "Conversation",
  c360TimelineNote: "Note",
  c360TimelineTask: "Task",
  c360OpenConversation: "Open conversation",
  c360NewOrder: "New order",
  c360CustomerSince: "Customer since",
  c360Default: "Default",
  c360Blocked: "Blocked",
  c360Active: "Active",
  viewAll: "View all",

  // Notifications centre (spec W5)
  notifications: "Notifications",
  notificationsHint: "Everything that reached you, grouped by kind",
  markAllRead: "Mark all as read",
  markAsRead: "Mark as read",
  markSelectedRead: "Mark selected as read",
  noNotifications: "No notifications",
  noNotificationsHint: "Anything that needs your attention will show up here.",
  filterAll: "All",
  filterUnread: "Unread",
  filterByKind: "By kind",
  selectedCount: (n: number) => `${n} selected`,
  allCaughtUp: "Nothing new",
  notificationsAllRead: "All notifications are read",
  toOpen: "to open",

  // §104 — confirmation for destructive actions
  confirm: "Confirm",
  confirmDescription: "Are you sure you want to do this? This cannot be undone.",
  revokeConfirmTitle: "Revoke invitation?",
  revokeConfirmBody: "The invitation will be revoked and can no longer be accepted. This cannot be undone.",
  revokeConfirmAction: "Revoke invitation",
  logoutConfirmTitle: "Sign out?",
  logoutConfirmBody: "You will need to sign in again to access your account.",
  deleteViewConfirmTitle: "Delete saved view?",
  deleteViewConfirmBody: (name: string) => `The view "${name}" will be deleted permanently. This cannot be undone.`,
  deleteViewConfirmAction: "Delete view",
  approveConfirmTitle: "Approve this action?",
  approveConfirmBody: "The high-risk AI action will run immediately once approved — review the details carefully.",
  rejectConfirmTitle: "Reject this action?",
  rejectConfirmBody: "The request will be rejected and closed. This cannot be undone.",
  rejectConfirmAction: "Confirm rejection",

  // §97 — my saved views
  mySavedViews: "My saved views",
  mySavedViewsHint: "Shortcuts to the filtered views you saved.",
  mySavedViewsEmpty: "No saved views",
  mySavedViewsEmptyHint: "Save a view from the customers or orders page and it will show up here.",
} as const;



const dictionaries: Record<Lang, Record<string, unknown>> = {
  ar,
  en: en as unknown as Record<string, unknown>,
};

/** Language-aware vocabulary proxy — reads the active language at access
 * time, so a reload after setLang() re-renders everything in that language
 * while the layout direction stays exactly as-is. */
export const t = makeT(dictionaries) as typeof ar;

export const languages: { code: Lang; label: string }[] = [
  { code: "ar", label: "العربية" },
  { code: "en", label: "English" },
];
