"""Imports every module's models so Base.metadata is complete.

Alembic env.py imports this single module — new domain model files must be
registered here or they will not appear in autogenerated migrations.
"""

from app.core.db import Base  # noqa: F401
from app.modules.ai import models as ai  # noqa: F401
from app.modules.automation import models as automation  # noqa: F401
from app.modules.billing import models as billing  # noqa: F401
from app.modules.catalog import models as catalog  # noqa: F401
from app.modules.conversations import models as conversations  # noqa: F401
from app.modules.customers import models as customers  # noqa: F401
from app.modules.decisions import models as decisions  # noqa: F401
from app.modules.evidence import models as evidence  # noqa: F401
from app.modules.identity import models as identity  # noqa: F401
from app.modules.inventory import models as inventory  # noqa: F401
from app.modules.marketing import models as marketing  # noqa: F401
from app.modules.operations import models as operations  # noqa: F401
from app.modules.orders import models as orders  # noqa: F401
from app.modules.platform import models as platform  # noqa: F401
from app.modules.privacy import models as privacy  # noqa: F401
from app.modules.segments.service import Segment  # noqa: F401  (model lives in service.py)
